server:
  port: ${BUG_TRACKER_SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

# My config variables
config:
  admin:
    ipAddress: ${MY_PUBLIC_IP_ADDRESS}