server:
  port: ${BUG_TRACKER_SERVER_PORT}
  servlet:
    session:
      timeout: 2
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

# My config variables
config:
  jwt:
    token:
      secret: ${TOKEN_SECRET}
      expired: ${TOKEN_EXPIRATION_TIME}


