server:
  port: ${BUG_TRACKER_SERVER_PORT:9000}
  servlet:
    session:
      timeout: -1
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USERNAME:postgres}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

# My config variables
config:
  jwt:
    token:
      secret: ${TOKEN_SECRET:secret}
      expired: ${TOKEN_EXPIRATION_TIME:1000000}


