export const BOARD_DATA_LOADING_START = 'BOARD_DATA_LOADING_START';
export const BOARD_DATA_LOAD = 'BOARD_DATA_LOAD';
export const BOARD_DATA_LOADING_END = 'BOARD_DATA_LOADING_END';
export const ON_DRAG_END = 'ON_DRAG_END';
export const ON_SAVE_NEW_CARD = 'ON_SAVE_NEW_CARD';
export const ON_ADD_NEW_COLUMN = 'ON_ADD_NEW_COLUMN';